### ISSUE TITLE
php artisan migrate:fresh doesn't work

### ISSUE THREAD

**Issue by larskoole** [singlestore-labs/singlestore-laravel-driver#3] opened 2022-06-01 08:13 UTC
As the title states, the command `php artisan migrate:fresh` doesn't work.

This also impacts unit tests which use the `RefreshDatabase` trait.

The error:
`SQLSTATE[HY000]: General error: 1295 This command is not supported in the prepared statement protocol yet (SQL: SHOW FULL TABLES WHERE table_type = 'BASE TABLE')`

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/8629456/171358705-af6d9edf-dbaf-486a-adb6-436fcbc3a5dc.png">

**Comment by fgilio** [comment] 2022-06-09 14:44
👋 found the issue, and it's actually documented in [SingleStore's "Connect with Laravel" doc](https://docs.singlestore.com/managed-service/en/developer-resources/connect-with-application-development-tools/connect-with-laravel.html).

We need to add this extra option to the database connection config: `PDO::ATTR_EMULATE_PREPARES => true`, [here is why](https://docs.singlestore.com/managed-service/en/developer-resources/connect-with-application-development-tools/using-prepared-statements.html).

With this change in place, then we get a second error which at least is crystal clear:
![Screen Shot 2022-06-09 at 11 38 06](https://user-images.githubusercontent.com/6857732/172875188-31e60db1-490a-40ba-b1b1-ce90743db061.png)

**Comment by fgilio** [comment] 2022-06-14 20:02
👋  I have some comments about `PDO::ATTR_EMULATE_PREPARES => true` that I think we should take into consideration and, at least, mention in the docs.

Up until PHP 8.1 the flag `PDO::ATTR_EMULATE_PREPARES` results in a bug by which all attributes returned by MySQL (or SingleStore that matter) are returned as strings.
Meaning that for a table with a column named `user_id` and a type of `int(10)`, if the row value is `5423` in Laravel we would get a string like `"5423"`.

This is a historic and known bug:
- https://stackoverflow.com/a/58830039/3275796
- https://github.com/php/php-src/blob/7b34db0659dda933b1146a0ff249f25acca1d669/UPGRADING#L130-L134

There are multiple solutions depending on the actual codebase, the two that I tested and consider the most appropriate are:
- Use [Eloquent's attribute casting](https://laravel.com/docs/9.x/eloquent-mutators#attribute-casting), much like when casting JSON to array. This gets gnarly if you have more than a handful of tables.
- Upgrade to PHP 8.1. If this is a viable option in the project at hand, this is the best course of action. This is what we're doing at publica.la.

I don't consider setting `PDO::ATTR_EMULATE_PREPARES => false` a true solution, as SingleStore requires it and this is caused by a bug already fixed in PHP 8.1.

-

Let me know if this makes sense!

**Comment by aarondfrancis** [comment] 2022-06-29 14:40
@fgilio this is really really helpful info, thank you for surfacing it. I agree that we should probably stick with setting the value to `true`, since that's the more correct way, and the issue will get smaller and smaller over time as people move to 8.1. I'll add some stuff to the docs to warn people.

**Closed** 2022-06-29 14:46 UTC
